version: "3.4"

services:
  Api:
    container_name: api
    image: api:latest
    build:
      context: .
      dockerfile: EComputer/Dockerfile
    depends_on:
      - redis
      - database
    # volumes:
    #   - ecomputer_image-storage:/app/wwwroot/images 
    ports:
      - "5000:5000"

  redis:
    container_name: redis
    image: redis:latest

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

# volumes:
#     ecomputer_image-storage: {}