
services:
  test:
    container_name: test
    image: test:latest
    build:
      context: .
      dockerfile: EComputer/Dockerfile
    depends_on:
      - redis
      - database

  redis:
    container_name: redis
    image: redis:latest

  database:
    container_name: database
    image: postgres:latest


    