Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information
AllowedHosts: '*'

Jwt:
  Audience: TestAudience
  Key: e444dff1ba68a27e327484b63b7da2c32a32fc7a52a4a0587fcb10dbfdac1b44
  RefreshTokenExpirationTimeMinutes: 4
  TokenExpirationTimeMinutes: 4
  Issuer: Test

#TODO : Implement IMAP
EmailSettings:
  Server: smtp.gmail.com
  Port: 587
  EnableSsl: true
  Email: nazarovruslan04@gmail.com
  Password: zanb axss upsa gvrk