name: Deploy to Docker Hub and Server
 
 on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./EComputer
          file: ./EComputer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecomputer:latest

      - name: Show images in Docker Hub
        run: |
          echo "Image pushed: ${{ secrets.DOCKERHUB_USERNAME }}/ecomputer:latest"
          echo "Check your Docker Hub repository for the image."

      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ecomputer:latest
            docker stop ecomputer || true
            docker rm ecomputer || true
            docker run -d --name ecomputer -p 5000:5000 -p 5001:5001 ${{ secrets.DOCKERHUB_USERNAME }}/ecomputer:latest 
